# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Serializer\CourseDenormalizer:
        arguments:
            $normalizer: '@serializer.normalizer.object'
        tags:
            - { name: 'serializer.normalizer', priority: 100 }
    
    App\Serializer\CourseNormalizer:
        arguments:
            $normalizer: '@serializer.normalizer.object'
        tags:
            - { name: 'serializer.normalizer', priority: 100 }
    
    # ExamVoucherDenormalizer désactivé - utilisation de la sérialisation standard
    # App\Serializer\ExamVoucherDenormalizer:
    #     arguments:
    #         $normalizer: '@serializer.normalizer.object'
    #     tags:
    #         - { name: 'serializer.normalizer', priority: 100 }
    
    App\Serializer\CircularReferenceHandler:
        class: App\Serializer\CircularReferenceHandler
    
    # Enregistrer explicitement le CourseProcessor
    App\State\CourseProcessor:
        autowire: true
        autoconfigure: true
    
    # ExamVoucherProcessor désactivé - utilisation du processor standard
    # App\State\ExamVoucherProcessor:
    #     autowire: true
    #     autoconfigure: true
    
    # Security Handlers
    App\Security\LoginSuccessHandler:
        autowire: true
        autoconfigure: true
    
    App\Security\LoginFailureHandler:
        autowire: true
        autoconfigure: true
    
    App\Security\AccessDeniedHandler:
        autowire: true
        autoconfigure: true

